services:
  data_load:
    build: ./src/data_load
    volumes:
      - ./data:/data
      - ./db:/db

  data_quality:
    build: ./src/data_quality
    depends_on:
      data_load:
        condition: service_completed_successfully
    volumes:
      - ./db:/db
      - ./reports:/reports

  research:
    build: ./src/research
    depends_on:
      data_quality:
        condition: service_completed_successfully
    volumes:
      - ./db:/db
      - ./reports:/reports

  visualize:
    build: ./src/visualize
    depends_on:
      research:
        condition: service_completed_successfully
    volumes:
      - ./db:/db
      - ./reports:/reports

  web:
    build: ./src/web
    ports:
      - "8000:5000"
    depends_on:
      visualize:
        condition: service_completed_successfully
    volumes:
      - ./reports:/reports
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      restart: unless-stopped

  node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      ports:
        - "9100:9100"
      restart: unless-stopped

  cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      container_name: cadvisor
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      restart: unless-stopped