#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - curl

runcmd:
  # 1. Встановлення Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh

  # 2. Клонування репозиторію
  - git clone https://github.com/RaDvyD/open-data-ai-analytics.git /home/ubuntu/app

  # 3. Запуск проєкту
  - cd /home/ubuntu/app
  - docker compose up --build -d